/** XVCbrain underwriting and transaction learning client. All work stays on the local instance. */
const $ = (selector, root=document) => root.querySelector(selector);
const $$ = (selector, root=document) => [...root.querySelectorAll(selector)];
const workspace = { tab:'report', properties:[], episodes:[], propertyId:'', episodeId:'', report:null, baselineReport:null, episode:null, models:[], activeModels:{}, propertySearch:'', scenario:null, initialized:false };
const moneyFields = new Set(['as_is_value','arv','estimated_repairs','gross_spread','partner_share','retained_fee','expenses','contribution','collected_cash','cash_required','expected_contribution','low','high','target','opening','maximum','company_receipts','cash_received','amount','purchase_price','price','acquisition_costs','transaction_costs']);
const nowInput = () => { const now=new Date(); return new Date(now.getTime()-now.getTimezoneOffset()*60000).toISOString().slice(0,19); };
const utc = value => value ? new Date(value).toISOString() : undefined;
const dateInput = field => field?.value ? field.getAttribute('data-auto-now')===field.value?new Date().toISOString():utc(field.value) : undefined;
function node(tag,attrs={},...children) { const result=document.createElement(tag);for(const [key,value] of Object.entries(attrs)){if(value==null)continue;if(key==='class')result.className=value;else if(key==='text')result.textContent=String(value);else if(key==='value')result.value=value;else if(key==='disabled')result.disabled=Boolean(value);else if(key.startsWith('on')&&typeof value==='function')result.addEventListener(key.slice(2).toLowerCase(),value);else result.setAttribute(key,String(value));}for(const child of children.flat())if(child!=null)result.append(child instanceof Node ? child : document.createTextNode(String(child)));return result; }
function fill(target,...children){(typeof target==='string'?$(target):target).replaceChildren(...children.flat().filter(Boolean));}
function numeric(value){const result=Number(value);return Number.isFinite(result)?result:0;}
function cash(value){return value==null||value===''?'Not established':new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(numeric(value));}
function percent(value){return value==null||value===''?'Not established':`${(numeric(value)*100).toFixed(1)}%`;}
function label(key){return String(key).replaceAll('_',' ').replace(/\b\w/g,char=>char.toUpperCase());}
function written(value,fallback='Not established'){return value==null||value===''?fallback:typeof value==='object'?JSON.stringify(value):String(value);}
function time(value){if(!value)return 'Not recorded';const parsed=new Date(value);return Number.isNaN(parsed.valueOf())?String(value):parsed.toLocaleString('en-US',{dateStyle:'medium',timeStyle:'short'});}
function rows(response){return Array.isArray(response)?response:response?.items||[];}
function badge(text,type='muted'){return node('span',{class:`tag ${type}`,text});}
function toast(message,error=false){const note=node('div',{class:`toast${error?' error':''}`,role:error?'alert':'status',text:message});$('#toast-stack').append(note);setTimeout(()=>note.remove(),7000);}
function blank(title,description){return node('div',{class:'empty-state'},node('div',{class:'empty-symbol',text:'◇'}),node('h3',{text:title}),node('p',{text:description}));}
function line(title,value,format){return node('div',{class:'report-line'},node('span',{text:title}),node('b',{text:format?format(value):written(value)}));}
function note(text){return text?node('p',{class:'report-note',text:Array.isArray(text)?text.map(value=>written(value)).join(' '):written(text)}):null;}
function list(values){if(!values)return null;const entries=Array.isArray(values)?values:typeof values==='object'?Object.entries(values).map(([key,value])=>`${label(key)}: ${written(value)}`):[values];return entries.length?node('ul',{class:'report-list'},entries.map(value=>node('li',{text:typeof value==='object'?value.message||value.reason||value.action||value.name||JSON.stringify(value):value}))):null;}
function advanced(title,value){return node('details',{class:'assumption-details'},node('summary',{text:title}),node('pre',{class:'detail-mono',text:JSON.stringify(value??{},null,2)}));}
function loading(target){fill(target,node('div',{class:'loading',text:'Loading underwriting intelligence'}));}
async function request(path,options={}){const headers=new Headers(options.headers||{});const token=sessionStorage.getItem('brain-api-token');if(token)headers.set('Authorization',`Bearer ${token}`);if(options.body)headers.set('Content-Type','application/json');const response=await fetch(path,{...options,headers});let data;try{data=await response.json();}catch{throw new Error(`Unexpected response (${response.status})`);}if(!response.ok)throw new Error(written(data.error?.message||data.error||data.detail,`${response.status}: Request failed`));return data;}
async function busy(button,task,text='Working…'){const previous=button.textContent;button.disabled=true;button.textContent=text;try{return await task();}catch(error){toast(error.message,true);return null;}finally{button.disabled=false;button.textContent=previous;}}
let fieldCounter=0;
function inputField(name,title,options={}){const {type='text',required=false,value='',choices,autoNow=false,...attrs}=options;const id=`brain-field-${name}-${++fieldCounter}`;const input=choices?node('select',{name,id},choices.map(choice=>node('option',{value:typeof choice==='string'?choice:choice[0],text:typeof choice==='string'?label(choice):choice[1]}))):type==='textarea'?node('textarea',{name,id,rows:3,...attrs}):node('input',{name,id,type,...(type==='datetime-local'?{step:1}:{}),...attrs});input.value=value;if(autoNow)input.setAttribute('data-auto-now',value);if(required)input.required=true;return node('label',{},title,input);}
function dialog(content,id){let dialogNode=$(`#${id}`);if(!dialogNode){dialogNode=node('dialog',{id,class:'brain-dialog'});document.body.append(dialogNode);dialogNode.addEventListener('click',event=>{if(event.target===dialogNode){const box=dialogNode.getBoundingClientRect();if(event.clientX<box.left||event.clientX>box.right||event.clientY<box.top||event.clientY>box.bottom)dialogNode.close();}});}fill(dialogNode,content);dialogNode.showModal();return dialogNode;}
function formHeading(title,eyebrow,onclose){return node('div',{class:'modal-heading'},node('div',{},node('p',{class:'eyebrow',text:eyebrow}),node('h2',{text:title})),node('button',{type:'button',class:'icon-button','aria-label':'Close dialog',onclick:onclose},'×'));}
function propertyName(id){return workspace.properties.find(item=>item.id===id)?.address||id||'Select a property';}
function eventData(event){return event.data||event.payload||{};}
const tabs=[['report','Live underwriting'],['ledger','Transaction ledger'],['documents','Documents'],['queue','Daily queue'],['portfolio','Portfolio cash'],['models','Model registry'],['rules','Contract rules']];

function initialize(){
  if(workspace.initialized)return;workspace.initialized=true;
  const root=$('#page-brain');
  root.append(node('div',{class:'page-heading compact brain-heading'},node('div',{},node('p',{class:'eyebrow',text:'101XVC PROPRIETARY INTELLIGENCE'}),node('h1',{id:'brain-title'},node('span',{text:'XVCbrain'}),' Underwriting Intelligence'),node('p',{class:'page-description',text:'Price the acquisition. Track the execution. Learn from settled economics. Independent models preserve the evidence behind every decision.'})),badge('LOCAL + INDEPENDENT','')),
    node('div',{class:'brain-tabs',role:'tablist','aria-label':'Underwriting intelligence views'},tabs.map(([key,title])=>node('button',{class:`brain-tab${key==='report'?' active':''}`,id:`brain-tab-${key}`,role:'tab','aria-selected':key==='report','aria-controls':`brain-view-${key}`,onclick:()=>switchTab(key)},title))),
    node('article',{class:'panel brain-context',id:'brain-context'},node('label',{class:'context-search'},'Find a property',node('input',{id:'brain-property-search',type:'search',placeholder:'Address, owner, or parcel'})),node('label',{},'Property',node('select',{id:'brain-property','aria-label':'Underwriting property'}),node('span',{class:'context-count',id:'brain-property-count'})),node('label',{},'Transaction episode',node('select',{id:'brain-episode','aria-label':'Transaction episode'})),node('div',{class:'context-actions'},node('button',{id:'brain-new-episode',class:'button',onclick:openEpisodeForm},'+ New episode'),node('button',{id:'brain-context-refresh',class:'button primary',onclick:event=>busy(event.currentTarget,refreshTab,'Refreshing…')},'Refresh →'))),
    ...tabs.map(([key])=>node('section',{id:`brain-view-${key}`,class:`brain-subview${key==='report'?' active':''}`,role:'tabpanel','aria-labelledby':`brain-tab-${key}`})));
  $('#brain-property').addEventListener('change',()=>{workspace.propertyId=$('#brain-property').value;workspace.episodeId='';workspace.scenario=null;renderEpisodeSelect();refreshTab().catch(showError);});
  $('#brain-episode').addEventListener('change',()=>{workspace.episodeId=$('#brain-episode').value;workspace.scenario=null;refreshTab().catch(showError);});
  let timer;$('#brain-property-search').addEventListener('input',()=>{clearTimeout(timer);timer=setTimeout(()=>searchProperties().catch(showError),250);});
}
function showError(error){toast(error.message,true);}
export async function loadBrain(){initialize();await refreshContext();await refreshTab();}
async function refreshContext(){const result=await Promise.allSettled([request(`/api/properties?limit=100&q=${encodeURIComponent($('#brain-property-search').value)}`),request('/api/brain/episodes')]);if(result[0].status==='fulfilled'){workspace.properties=rows(result[0].value);if(workspace.propertyId&&!workspace.properties.some(property=>property.id===workspace.propertyId)){try{const detail=await request(`/api/properties/${encodeURIComponent(workspace.propertyId)}`);workspace.properties.unshift(detail.property||detail);}catch{/* Selection no longer exists. */}}renderPropertySelect(result[0].value.total);}else throw result[0].reason;if(result[1].status==='fulfilled')workspace.episodes=rows(result[1].value);else{workspace.episodes=[];toast(`Transaction ledger unavailable: ${result[1].reason.message}`,true);}renderEpisodeSelect();}
async function searchProperties(){const query=$('#brain-property-search').value;const result=await request(`/api/properties?limit=100&q=${encodeURIComponent(query)}`);workspace.properties=rows(result);renderPropertySelect(result.total);renderEpisodeSelect();}
function renderPropertySelect(total){const select=$('#brain-property');fill(select,node('option',{value:'',text:'Select a property'}),workspace.properties.map(property=>node('option',{value:property.id,text:`${property.synthetic?'DEMO · ':''}${property.address||property.id}`})));if(workspace.properties.some(item=>item.id===workspace.propertyId))select.value=workspace.propertyId;else{workspace.propertyId=workspace.properties[0]?.id||'';select.value=workspace.propertyId;}$('#brain-property-count').textContent=`${workspace.properties.length} shown${total>workspace.properties.length?` of ${total}; refine the search`:''}`;}
function renderEpisodeSelect(){const select=$('#brain-episode');const episodes=workspace.episodes.filter(item=>item.property_id===workspace.propertyId);fill(select,node('option',{value:'',text:episodes.length?'Auto-select latest transaction':'Property view (no episode)'}),episodes.map(item=>node('option',{value:item.id||item.episode_id,text:`${label(item.stage||'intake')} · ${item.id||item.episode_id}`})));if(episodes.some(item=>(item.id||item.episode_id)===workspace.episodeId))select.value=workspace.episodeId;else{workspace.episodeId=episodes[0]?.id||episodes[0]?.episode_id||'';select.value=workspace.episodeId;}}
async function switchTab(key){workspace.tab=key;$$('.brain-tab').forEach(tab=>{const active=tab.id===`brain-tab-${key}`;tab.classList.toggle('active',active);tab.setAttribute('aria-selected',String(active));});$$('.brain-subview').forEach(view=>view.classList.toggle('active',view.id===`brain-view-${key}`));$('#brain-context').classList.toggle('hidden',['queue','portfolio','models','rules'].includes(key));await refreshTab().catch(showError);}
async function refreshTab(){const loaders={report:loadReport,ledger:loadLedger,documents:loadDocuments,queue:loadQueue,portfolio:loadPortfolio,models:loadModels,rules:loadRules};try{await loaders[workspace.tab]();}catch(error){fill(`#brain-view-${workspace.tab}`,node('div',{class:'brain-banner error',text:error.message}),node('button',{class:'button',onclick:event=>busy(event.currentTarget,refreshTab,'Retrying…')},'Retry this view'));throw error;}}

async function loadReport(){
  if(!workspace.propertyId){fill('#brain-view-report',blank('Import properties to begin underwriting','The live report requires a canonical property record. Import your data in Source network or load clearly labeled demo records.'));return;}
  loading('#brain-view-report');
  const query=workspace.episodeId?`?episode_id=${encodeURIComponent(workspace.episodeId)}`:'';
  const path=`/api/brain/report/${encodeURIComponent(workspace.propertyId)}${query}`;
  let report;
  if(workspace.scenario){const result=await Promise.all([request(path),request(path,{method:'POST',body:JSON.stringify({episode_id:workspace.episodeId||undefined,scenario:workspace.scenario})})]);workspace.baselineReport=result[0];report=result[1];}
  else{report=await request(path);workspace.baselineReport=report;}
  if(report.episode_id&&!workspace.episodeId){workspace.episodeId=report.episode_id;$('#brain-episode').value=workspace.episodeId;}
  workspace.report=report;renderReport(report);
}
function renderReport(report){
  const valuation=report.valuation||{},condition=report.condition||{},exit=report.exit_price||{},offer=report.offer||{},acceptance=report.seller_acceptance||{},closing=report.closing||{},economics=report.company_economics||{},next=report.next_action||{},evidence=report.evidence||{};
  const synthetic=workspace.properties.find(item=>item.id===workspace.propertyId)?.synthetic||report.synthetic;
  const blocked=offer.recommendation_status==='blocked_by_reviewed_rule_or_resource_constraint';
  const central=node('article',{class:'brain-central'},node('div',{class:'brain-central-top'},node('div',{},node('p',{class:'eyebrow',text:workspace.scenario?'SCENARIO UNDERWRITING':'LIVE UNDERWRITING RECOMMENDATION'}),node('h2',{text:blocked?'Resolve the commitment constraints first':offer.target==null?'The acquisition price is not established':`Target contract price ${cash(offer.target)}`}),node('p',{text:label(next.action||'Collect the required evidence before committing to this acquisition.')}),note(next.reason)),badge(synthetic?'SYNTHETIC PROPERTY':label(offer.recommendation_status||offer.objective_status||'Evidence-based estimate'),synthetic?'':'muted')),node('div',{class:'central-metrics'},metric('MAXIMUM ACQUISITION PRICE',cash(offer.maximum)),metric('EXPECTED CONTRIBUTION',cash(economics.expected_contribution)),metric('FUNDED CLOSING LIKELIHOOD',percent(closing.probability)),metric('CASH REQUIRED',cash(economics.cash_required))));
  const grid=node('div',{class:'brain-report-grid'},
    reportCard('01 · PROPERTY VALUATION','Separate the value estimates',line('Estimated as-is value',valuation.as_is_value,cash),line('Estimated ARV',valuation.arv,cash),line('Value uncertainty range',rangeText(valuation.range)),note(valuation.status),missing(valuation.missing),valuation.comps?.length?advanced('Inspect valuation comparables',valuation.comps):null),
    reportCard('02 · CONDITION + REPAIRS','Inspect before committing',line('Estimated repair cost',condition.estimated_repairs,cash),line('Repair uncertainty range',rangeText(condition.range)),list(condition.inspection_priorities),missing(condition.missing),condition.scenarios?advanced('Review repair scenarios',condition.scenarios):null),
    reportCard('03 · DISPOSITION LIQUIDITY','Executable exit evidence',line('Estimated executable exit',exit.target,cash),line('Disposition price range',rangeText({low:exit.low,high:exit.high})),line('Executable bids',Array.isArray(exit.executable_bids)?exit.executable_bids.length:exit.executable_bids??'Not established'),line('Stated interest',Array.isArray(exit.stated_interest)?exit.stated_interest.length:exit.stated_interest??'Not established'),note(exit.status),report.liquidity?advanced('Inspect demand and capacity',report.liquidity):null),
    reportCard('04 · PRICE + TERMS','Offer and negotiation range',line('Opening offer',offer.opening,cash),line('Target contract price',offer.target,cash),line('Counteroffer range',rangeText(offer.counter_range)),line('Maximum acceptable price',offer.maximum,cash),note(offer.objective_status),offer.constraints?renderConstraints(offer.constraints):null,offer.candidates?advanced('Compare evaluated offer candidates',offer.candidates):null),
    reportCard('05 · SELLER RESPONSE','Acceptance evidence',line('Estimated acceptance probability',acceptance.probability,percent),note(acceptance.status),acceptance.model_id?line('Model version',acceptance.model_id):null,acceptance.by_offer?advanced('Acceptance estimates by offer',acceptance.by_offer):null,report.seller_notes?advanced('Inspect seller notes',report.seller_notes):null),
    reportCard('06 · TRANSACTION ECONOMICS','Retained receipts after expenses',line('Estimated gross spread',economics.gross_spread,cash),line('Partner share',economics.partner_share,cash),line('101XVC retained fee',economics.retained_fee,cash),line('Attributable expenses',typeof economics.expenses==='object'?economics.expenses?.attributable:economics.expenses,cash),line('Estimated contribution',economics.contribution,cash),line('Probability-weighted contribution',economics.expected_contribution,cash),line('Collected cash',economics.collected_cash,cash),note(economics.status),economics.downside?advanced('Inspect downside exposure',economics.downside):null),
    reportCard('07 · CLOSING + FAILURE','Timing and competing outcomes',line('Funded closing probability',closing.probability,percent),line('Before deadline',closing.deadline_probability,percent),note(closing.status),renderTimeline(closing.timeline),closing.failure_risk?advanced('Inspect failure risk estimates',closing.failure_risk):null),
    reportCard('08 · NEXT ACTION','Improve the transaction',node('div',{class:'report-risk'},node('b',{text:label(next.action||'No supported intervention yet')}),written(next.reason,'Collect the missing evidence and refresh this report.')),line('Priority',next.priority),report.value_of_information?advanced('Value of additional information (scenario bound)',report.value_of_information):null,report.rules?advanced('Applicable contract rules',report.rules):null),
    reportCard('09 · EVIDENCE + ASSUMPTIONS','Know what could change the decision',line('Report effective time',time(report.as_of)),line('Transaction stage',label(report.stage||'property review')),evidence.freshness?note(`Freshness: ${written(evidence.freshness)}`):null,evidence.conflicts?advanced('Review source conflicts',evidence.conflicts):null,advanced('Supporting sources and field provenance',evidence),advanced('Recorded assumptions',report.assumptions),advanced('Model versions used',report.model_versions)));
  grid.lastElementChild.classList.add('wide');
  const scenario=createScenarioPanel();
  const status=node('div',{class:'brain-status-line'},node('span',{text:propertyName(workspace.propertyId)}),badge(workspace.episodeId?`EPISODE ${workspace.episodeId}`:'PROPERTY VIEW','muted'),badge(workspace.scenario?'SCENARIO ACTIVE':'CURRENT EVIDENCE','muted'),node('span',{text:`As of ${time(report.as_of)}`}),node('button',{class:'button small',id:'brain-save-decision',onclick:openDecisionForm},'Save decision snapshot'));
  fill('#brain-view-report',status,central,workspace.scenario?renderScenarioComparison(report,workspace.baselineReport):null,node('div',{class:'brain-report-layout'},grid,scenario));
}
function metric(title,value){return node('div',{class:'central-metric'},node('span',{text:title}),node('b',{text:value}));}
function reportCard(eyebrow,title,...content){return node('article',{class:'report-card'},node('p',{class:'eyebrow',text:eyebrow}),node('h3',{text:title}),...content);}
function missing(values){if(!values||!values.length)return null;return node('p',{class:'report-missing',text:`Missing evidence: ${Array.isArray(values)?values.map(value=>written(value)).join('; '):written(values)}`});}
function renderConstraints(constraints){return node('div',{},line('Cash constraint',label(constraints.cash_status||'not configured')),line('Execution capacity',label(constraints.capacity_status||'not configured')),constraints.missing_required_documents?.length?missing(constraints.missing_required_documents):null,advanced('Inspect all acquisition constraints',constraints));}
function renderScenarioComparison(report,baseline) {
  const pairs = [
    ['Acquisition ceiling',baseline?.offer?.maximum,report.offer?.maximum],
    ['Retained fee',baseline?.company_economics?.retained_fee,report.company_economics?.retained_fee],
    ['Contribution',baseline?.company_economics?.contribution,report.company_economics?.contribution],
    ['Expected contribution',baseline?.company_economics?.expected_contribution,report.company_economics?.expected_contribution]
  ];
  const header = node('thead', {}, node('tr', {},
    ...['OUTPUT','CURRENT EVIDENCE','SCENARIO','CHANGE'].map(title=>node('th',{text:title}))
  ));
  const body = node('tbody', {}, pairs.map(([title,before,after]) => node('tr', {},
    node('td',{text:title}),
    node('td',{text:cash(before)}),
    node('td',{text:cash(after)}),
    node('td',{text:before==null||after==null?'Not established':cash(after-before)})
  )));
  return node('article', {class:'panel scenario-comparison'},
    node('div', {class:'panel-heading'}, node('div', {},
      node('p',{class:'eyebrow',text:'CURRENT EVIDENCE / YOUR SCENARIO'}),
      node('h2',{text:'Compare the decision'})
    )),
    node('div', {class:'table-wrap'}, node('table', {}, header, body))
  );
}
function rangeText(range){if(!range)return 'Not established';if(Array.isArray(range))return range.length>=2?`${cash(range[0])} to ${cash(range[1])}`:'Not established';if(typeof range==='object'){const low=range.low??range.lower??range.min,high=range.high??range.upper??range.max;return low==null&&high==null?'Not established':`${cash(low)} to ${cash(high)}`;}return written(range);}
function renderTimeline(timeline){if(!timeline||!Object.keys(timeline).length)return note('Closing-time model is not established. Record dated outcomes and keep open episodes censored.');return node('div',{class:'table-wrap'},node('table',{class:'report-timeline'},node('thead',{},node('tr',{},...['WINDOW','CLOSED','CANCELLED','EXPIRED','OPEN'].map(title=>node('th',{text:title})))),node('tbody',{},Object.entries(timeline).map(([days,value])=>node('tr',{},node('td',{text:`${days} days`}),...['closed','cancelled','expired','still_open'].map(key=>node('td',{text:percent(value?.[key])})))))));}
function createScenarioPanel(){
  const values=workspace.scenario||{};
  const fields=[['additional_expenses','Additional attributable costs ($)'],['loss_exposure','Additional failure exposure ($)'],['cash_available','Available company cash ($)'],['capacity','Execution capacity slots'],['information_cost','Cost of additional investigation ($)'],['stale_after_days','Source freshness threshold (days)']];
  const form=node('form',{class:'stack-form',id:'brain-scenario-form'},inputField('exit_price_factor','Disposition price multiplier',{type:'number',min:0,max:2,step:.01,value:values.exit_price_factor??'',placeholder:'1.00 = recorded bid prices'}),...fields.map(([name,title])=>inputField(name,title,{type:'number',min:0,step:name==='capacity'||name==='stale_after_days'?1:100,value:values[name]??'',placeholder:'Use current evidence'})),node('div',{class:'form-pair'},inputField('repair_low','Low repair scenario ($)',{type:'number',min:0,value:values.repair_scenarios?.low??''}),inputField('repair_high','High repair scenario ($)',{type:'number',min:0,value:values.repair_scenarios?.high??''})),node('label',{class:'checkbox-label'},node('input',{type:'checkbox',name:'expenses_complete',id:'brain-scenario-zero-cost',...(values.expenses_complete?{checked:'checked'}:{})}),'Explicit zero-cost assumption if no costs recorded'),node('button',{type:'submit',class:'button primary',id:'brain-run-scenario'},'Evaluate scenario →'),node('button',{type:'button',class:'button',id:'brain-reset-scenario',onclick:event=>busy(event.currentTarget,async()=>{workspace.scenario=null;await loadReport();})},'Restore current evidence'));
  form.addEventListener('submit',event=>{event.preventDefault();busy($('button[type=submit]',form),async()=>{const values={};for(const [key,value] of new FormData(form)){if(value==='')continue;if(key==='expenses_complete'){values.expenses_complete=true;continue;}if(key.startsWith('repair_')){values.repair_scenarios??={};values.repair_scenarios[key.slice(7)]=numeric(value);}else values[key]=numeric(value);}if(!Object.keys(values).length)throw new Error('Enter at least one scenario assumption.');workspace.scenario=values;await loadReport();},'Evaluating…');});
  return node('article',{class:'panel scenario-panel'},node('div',{class:'panel-heading'},node('div',{},node('p',{class:'eyebrow',text:'WHAT CHANGES THE DECISION?'}),node('h2',{text:'Scenario desk'}))),form,node('p',{class:'scenario-note',text:'Scenario assumptions are separated from source evidence. They do not replace verified fields or automatically change transaction records. Save a snapshot to retain the decision context.'}));
}

function openEpisodeForm(){
  if(!workspace.propertyId){toast('Select an imported property before creating a transaction episode.',true);return;}
  let modal;const form=node('form',{id:'brain-create-episode-form'},formHeading('Start a transaction episode','PERMANENT LEARNING RECORD',()=>modal.close()),node('p',{class:'form-note',text:propertyName(workspace.propertyId)}),inputField('stage','Initial stage',{choices:['intake','contacted','offered','contracted','diligence','disposition','closing'],value:'intake'}),node('div',{class:'form-pair'},inputField('intake_date','Intake date',{type:'datetime-local',required:true,value:nowInput()}),inputField('deadline','Contract deadline',{type:'datetime-local'})),node('div',{class:'form-pair'},inputField('asking_price','Seller asking price ($)',{type:'number',min:0,step:100}),inputField('target_price','Target price ($)',{type:'number',min:0,step:100})),node('div',{class:'form-pair'},inputField('partner_id','Disposition partner'),inputField('buyer_id','Known buyer')),inputField('capacity','Execution capacity slots',{type:'number',min:0,step:1}),node('p',{class:'form-note',text:'Episodes and their events are permanent audit records. Archive through a recorded update or terminal outcome rather than deleting evidence.'}),node('div',{class:'modal-actions'},node('button',{type:'button',class:'button',onclick:()=>modal.close()},'Cancel'),node('button',{type:'submit',class:'button primary',id:'brain-create-episode'},'Create episode')));
  form.addEventListener('submit',event=>{event.preventDefault();busy($('button[type=submit]',form),async()=>{const data=Object.fromEntries(new FormData(form));for(const key of Object.keys(data))if(data[key]==='')delete data[key];for(const key of ['asking_price','target_price','capacity'])if(data[key]!=null)data[key]=numeric(data[key]);for(const key of ['intake_date','deadline'])if(data[key])data[key]=utc(data[key]);data.property_id=workspace.propertyId;data.state=workspace.properties.find(item=>item.id===workspace.propertyId)?.state;const result=await request('/api/brain/episodes',{method:'POST',body:JSON.stringify(data)});const episode=result.episode||result;workspace.episodeId=episode.id||episode.episode_id;modal.close();await refreshContext();toast('Transaction episode created.');await switchTab('ledger');},'Creating…');});
  modal=dialog(form,'brain-episode-dialog');
}
async function loadLedger(){
  const response=await request('/api/brain/episodes');workspace.episodes=rows(response);renderEpisodeSelect();
  const relevant=workspace.propertyId?workspace.episodes.filter(item=>item.property_id===workspace.propertyId):workspace.episodes;
  const cards=relevant.length?relevant.map(episode=>node('button',{type:'button',class:`episode-card${(episode.id||episode.episode_id)===workspace.episodeId?' active':''}`,onclick:async()=>{workspace.episodeId=episode.id||episode.episode_id;workspace.propertyId=episode.property_id;renderEpisodeSelect();await loadLedger().catch(showError);}},node('div',{class:'episode-card-head'},node('h3',{text:propertyName(episode.property_id)}),badge(label(episode.stage||'intake'),'muted')),node('p',{text:`Intake ${time(episode.intake_date||episode.created_at)}\nDeadline ${time(episode.deadline)}`}),node('small',{text:episode.id||episode.episode_id}))):[blank('No transaction episodes yet','Create an episode to preserve offers, bids, expenses, settlements, and outcomes for this property.')];
  const detail=node('article',{class:'panel ledger-content',id:'brain-ledger-detail'});
  fill('#brain-view-ledger',node('div',{class:'brain-action-heading'},node('h2',{text:'Every action. Every outcome.'}),node('button',{class:'button small',onclick:openEpisodeForm},'+ Start episode')),node('div',{class:'brain-ledger-layout'},node('div',{class:'episode-list',id:'brain-episode-list'},cards),detail));
  if(!workspace.episodeId){fill(detail,blank('Select an episode','Your transaction record connects evidence, actions, outcomes, and settled economics.'));return;}
  loading(detail);const responseDetail=await request(`/api/brain/episodes/${encodeURIComponent(workspace.episodeId)}`);workspace.episode=responseDetail;renderLedgerDetail(detail,responseDetail);
}
const eventSchemas={
  offer:[['price','Offer price ($)','number',true],['response','Seller response','select',true,['pending','accepted','rejected','counter']],['counter_price','Counteroffer ($)','number'],['terms','Terms / conditions','textarea'],['response_at','Response date','datetime-local']],
  bid:[['price','Bid price ($)','number',true],['status','Bid status','select',true,['interest','executable','accepted','funded']],['buyer_id','Buyer identifier','text'],['partner_id','Partner identifier','text'],['conditions','Conditions','textarea'],['expires_at','Bid expires','datetime-local']],
  milestone:[['name','Milestone / document','text',true],['status','Status','select',true,['pending','in_progress','completed','cleared','blocked','failed','waived','missing']],['due_date','Due date','datetime-local'],['completed_at','Completed date','datetime-local'],['document_id','Evidence document ID','text'],['verified','Evidence verified?','select',false,[['false','Unverified / pending'],['true','Verified by qualified source']]],['notes','Evidence / qualified feedback','textarea']],
  expense:[['amount','Amount ($)','number',true],['type','Attributable cost category','select',true,['acquisition','lead_generation','inspection','title','transaction','repairs','holding','marketing','other']],['paid','Cash paid?','select',true,[['false','Not yet / unknown'],['true','Paid']]],['paid_at','Paid date','datetime-local'],['description','Cost description','textarea']],
  settlement:[['gross_spread','Gross transaction spread ($)','number',true],['partner_share','Partner share ($)','number',true],['company_receipts','101XVC retained receipts ($)','number',true],['cash_received','Actual cash received ($)','number'],['closed_at','Funded closing date','datetime-local',true],['cash_received_at','Cash received date','datetime-local'],['acquisition_costs','Attributable acquisition costs ($)','number',true],['transaction_costs','Transaction costs ($)','number',true],['verified_as_is_value','Verified as-is transaction value ($)','number'],['actual_repairs','Verified actual repair cost ($)','number'],['supersedes_event_id','Correction of settlement event ID','text'],['notes','Settlement source / reference','textarea']],
  note:[['text','Source note / transcript excerpt','textarea',true],['source','Note source','text']],
  outcome:[['status','Observed outcome','select',true,['open','closed','cancelled','expired']],['occurred_at','Outcome date','datetime-local',true],['reason','Observed outcome reason','textarea',true]],
  update:[['stage','Transaction stage','select',true,['intake','contacted','offered','contracted','diligence','disposition','closing','archived']],['reason','Update / override reason','textarea',true],['asking_price','Updated asking price ($)','number'],['target_price','Updated target price ($)','number'],['deadline','Updated deadline','datetime-local']],
  action:[['action','Actual action taken','textarea',true],['actor','Person responsible','text'],['reason','Decision reason','textarea']],
};
function renderLedgerDetail(target,detail){
  const episode=detail.episode||detail,events=detail.events||[];const settlementCount=(detail.settlements||events.filter(event=>(event.kind||event.type)==='settlement')).length;
  const summary=node('div',{class:'ledger-summary'},node('div',{class:'source-card-top'},node('h3',{text:propertyName(episode.property_id)}),badge(label(episode.stage||'intake'),'muted')),node('p',{text:`Episode ${episode.id||episode.episode_id}\nEvents preserve observed time and availability time for later training.`}),line('Intake',time(episode.intake_date)),line('Contract deadline',time(episode.deadline)),line('Partner',episode.partner_id),line('Recorded settlement entries',settlementCount));
  const form=node('form',{id:'brain-event-form'},node('div',{class:'event-selector-row'},node('label',{},'Record a transaction event',node('select',{id:'brain-event-kind',name:'kind'},Object.keys(eventSchemas).map(kind=>node('option',{value:kind,text:label(kind)}))))),node('div',{class:'event-fields',id:'brain-event-fields'}),node('div',{class:'event-dates'},inputField('observed_at','When the event happened',{type:'datetime-local',required:true,value:nowInput(),autoNow:true}),inputField('available_at','When the information became available',{type:'datetime-local',required:true,value:nowInput(),autoNow:true})),node('details',{class:'advanced-event'},node('summary',{text:'Additional typed event details'}),inputField('extra','Additional fields (JSON object)',{type:'textarea',placeholder:'Optional additional structured evidence'})),node('div',{class:'event-form-footer'},node('p',{class:'form-note',id:'brain-event-note',text:'Record the actual source result. Missing values remain unknown.'}),node('button',{type:'submit',class:'button primary',id:'brain-record-event'},'Record event →')));
  const renderFields=()=>{const kind=$('#brain-event-kind').value;const descriptors=eventSchemas[kind];fill('#brain-event-fields',...descriptors.map(([name,title,type,required,choices])=>{const field=inputField(`data_${name}`,title,{type:type==='select'?'text':type,required:Boolean(required),choices,value:choices?typeof choices[0]==='string'?choices[0]:choices[0][0]:'',...(type==='number'?{min:0,step:.01}:{}),...(type==='datetime-local'&&name==='occurred_at'?{value:nowInput(),autoNow:true}:{} )});if(type==='textarea')field.classList.add('span-two');return field;}));$('#brain-event-note').textContent=kind==='settlement'?'Gross spread must equal partner share plus 101XVC retained receipts. A received-cash date requires actual cash received. Corrections reference the superseded event.':kind==='outcome'?'A closed outcome requires a recorded settlement. Still-open episodes are retained as ongoing observations.':'Record the actual source result. Missing values remain unknown.';};
  $('#brain-event-kind',form)?.addEventListener('change',renderFields);
  form.addEventListener('submit',event=>{event.preventDefault();busy($('button[type=submit]',form),async()=>{const kind=$('#brain-event-kind').value;let data={};for(const [name,title,type] of eventSchemas[kind]){const field=form.elements.namedItem(`data_${name}`);if(!field||field.value==='')continue;data[name]=type==='number'?numeric(field.value):type==='datetime-local'?dateInput(field):['paid','verified','required'].includes(name)?field.value==='true':field.value;}const extra=form.elements.namedItem('extra').value.trim();if(extra){const parsed=JSON.parse(extra);if(!parsed||typeof parsed!=='object'||Array.isArray(parsed))throw new Error('Additional details must be a JSON object.');Object.assign(data,parsed);}if(kind==='update'){const reason=data.reason;delete data.reason;data={changes:data,reason};}if(kind==='bid'&&typeof data.conditions==='string')data.conditions=data.conditions.split('\n').map(text=>text.trim()).filter(Boolean).map(text=>({description:text,status:'pending'}));if(kind==='settlement'){const meta={...(data.meta||{})};if(data.verified_as_is_value!=null){meta.as_is_value=data.verified_as_is_value;delete data.verified_as_is_value;}if(data.actual_repairs!=null){meta.actual_repairs=data.actual_repairs;delete data.actual_repairs;}if(Object.keys(meta).length)data.meta=meta;if(Math.abs(numeric(data.gross_spread)-numeric(data.partner_share)-numeric(data.company_receipts))>.01)throw new Error('Gross spread must equal partner share plus 101XVC retained receipts.');if(data.cash_received_at&&data.cash_received==null)throw new Error('Enter the actual cash received amount for the cash receipt date.');if(data.cash_received>0&&!data.cash_received_at)throw new Error('Record the date cash was actually received.');}if(kind==='expense'&&data.paid_at&&!data.paid)throw new Error('A paid date requires the expense to be marked paid.');if(kind==='outcome'&&data.status==='closed'&&!settlementCount)throw new Error('Record a settlement before marking this episode closed.');const event={kind,data,observed_at:dateInput(form.elements.namedItem('observed_at')),available_at:dateInput(form.elements.namedItem('available_at'))};await request(`/api/brain/episodes/${encodeURIComponent(workspace.episodeId)}/events`,{method:'POST',body:JSON.stringify(event)});toast(`${label(kind)} event recorded in the learning ledger.`);await loadLedger();},'Recording…');});
  const history=node('section',{class:'event-history'},node('h3',{text:'Permanent event history'}),events.length?events.slice().reverse().map(event=>{const data=eventData(event);return node('article',{class:'event-history-item'},node('span',{class:'event-icon',text:(event.kind||event.type)==='settlement'?'$':'◇'}),node('div',{},node('b',{text:label(event.kind||event.type||'event')}),node('small',{text:`Observed ${time(event.observed_at||event.occurred_at)} · available ${time(event.available_at||event.created_at)}`}),node('p',{text:eventSummary(event)}),advanced('Inspect recorded evidence',data)));}):note('No events recorded yet.'),detail.decisions?.length?advanced('Immutable decision snapshots',detail.decisions):null);
  fill(target,summary,form,history);renderFields();
}
function eventSummary(event){const data=eventData(event),kind=event.kind||event.type;if(kind==='offer')return `${cash(data.price)} · ${label(data.response||'pending')}${data.counter_price!=null?` · counter ${cash(data.counter_price)}`:''}`;if(kind==='bid')return `${cash(data.price)} · ${label(data.status||'interest')} · ${data.buyer_id||'Buyer unspecified'}`;if(kind==='expense')return `${cash(data.amount)} · ${label(data.type||data.category||'expense')}${data.paid?' · paid':''}`;if(kind==='settlement')return `Gross ${cash(data.gross_spread)} · 101XVC ${cash(data.company_receipts)} · collected ${cash(data.cash_received)}`;if(kind==='outcome')return `${label(data.status||'open')} · ${data.reason||'Reason not recorded'}`;if(kind==='milestone')return `${data.name||'Milestone'} · ${label(data.status||'pending')}`;return data.text||data.action||data.reason||data.notes||written(data);}

function openDecisionForm(){
  if(!workspace.episodeId){toast('Create or select an episode before preserving a decision snapshot.',true);return;}
  if(!workspace.report){toast('Load a live report before saving its decision context.',true);return;}
  let modal;const report=structuredClone(workspace.report);const form=node('form',{id:'brain-decision-form'},formHeading('Preserve this decision','IMMUTABLE LEARNING SNAPSHOT',()=>modal.close()),node('p',{class:'form-note',text:'The report, evidence available at the time, recommendation, and model versions are retained together. Future evidence does not overwrite this prediction.'}),inputField('action','Actual action / planned intervention',{type:'textarea',placeholder:'Record what was actually done, or leave blank to save the prediction before action.'}),inputField('decision_at','Decision date',{type:'datetime-local',required:true,value:nowInput(),autoNow:true}),node('div',{class:'modal-actions'},node('button',{type:'button',class:'button',onclick:()=>modal.close()},'Cancel'),node('button',{type:'submit',class:'button primary'},'Save immutable snapshot')));
  form.addEventListener('submit',event=>{event.preventDefault();busy($('button[type=submit]',form),async()=>{const action=form.elements.namedItem('action').value.trim();const features=report.decision_features||report.feature_snapshot||report.features;if(!features||!Object.keys(features).length)throw new Error('This report did not supply decision-time features. Refresh the report before recording a trainable snapshot.');const payload={prediction:report,recommendation:report.next_action||{},evidence_snapshot:{property_id:report.property_id,as_of:report.as_of,evidence:report.evidence,features,features_available_at:report.features_available_at||report.as_of,assumptions:report.assumptions,scenario:workspace.scenario},model_versions:report.model_versions||{},decision_at:dateInput(form.elements.namedItem('decision_at')),...(action?{action:{description:action}}:{})};await request(`/api/brain/episodes/${encodeURIComponent(workspace.episodeId)}/decisions`,{method:'POST',body:JSON.stringify(payload)});modal.close();toast('Decision snapshot preserved.');},'Saving…');});modal=dialog(form,'brain-decision-dialog');
}

async function loadDocuments(){
  loading('#brain-view-documents');
  const query=workspace.propertyId?`?property_id=${encodeURIComponent(workspace.propertyId)}`:'';
  const response=await request(`/api/documents${query}`);
  const entries=rows(response);
  const upload=node('form',{id:'brain-document-form',class:'document-upload-form'},inputField('file','Evidence file',{type:'file',required:true}),node('div',{class:'form-pair'},inputField('property_id','Linked property identifier',{value:workspace.propertyId}),inputField('episode_id','Linked episode identifier',{value:workspace.episodeId})),node('p',{class:'form-note',text:'Upload original inspection, title, contract, or settlement evidence. Files remain on your infrastructure. The maximum file size is 10 MiB. Linking a file does not verify its contents.'}),node('button',{type:'submit',class:'button primary',id:'brain-upload-document'},'Save evidence document →'));
  upload.addEventListener('submit',event=>{event.preventDefault();busy($('button[type=submit]',upload),async()=>{
    const file=upload.elements.namedItem('file').files[0];if(!file)throw new Error('Choose an evidence file.');if(!file.size||file.size>10*1024*1024)throw new Error('Evidence documents must contain data and be no larger than 10 MiB.');
    const encoded=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).slice(String(reader.result).indexOf(',')+1));reader.onerror=()=>reject(new Error('The selected file could not be read.'));reader.readAsDataURL(file);});
    const payload={filename:file.name,media_type:file.type||'application/octet-stream',content_base64:encoded};for(const key of ['property_id','episode_id'])if(upload.elements.namedItem(key).value.trim())payload[key]=upload.elements.namedItem(key).value.trim();
    const result=await request('/api/documents',{method:'POST',body:JSON.stringify(payload)});await loadDocuments();toast(`Evidence document saved. ID ${String(result.id||result.document?.id||'').slice(0,12)}…`);
  },'Uploading…');});
  const cards=entries.map(document=>node('article',{class:'document-card'},node('div',{class:'source-card-top'},node('span',{class:'source-card-icon',text:'▧'}),badge(document.media_type||'FILE','muted')),node('h3',{text:document.filename||'Evidence document'}),node('p',{text:`${(numeric(document.bytes)/1024).toFixed(1)} KiB · uploaded ${time(document.created_at)}`}),node('small',{text:`SHA256 ${document.sha256||document.id}`}),node('div',{class:'document-actions'},node('button',{class:'button small',id:`brain-document-download-${document.id}`,onclick:event=>busy(event.currentTarget,()=>downloadDocument(document.id),'Downloading…')},'↓ Download'),node('button',{class:'button small',onclick:event=>busy(event.currentTarget,async()=>{await navigator.clipboard.writeText(document.id);toast('Document identifier copied.');},'Copying…')},'Copy ID'),node('button',{class:'button small primary',onclick:async()=>{if(!workspace.episodeId){toast('Select an episode to link this evidence to a milestone.',true);return;}await switchTab('ledger');$('#brain-event-kind').value='milestone';$('#brain-event-kind').dispatchEvent(new Event('change'));$('#brain-event-form').elements.namedItem('data_document_id').value=document.id;$('#brain-event-form').elements.namedItem('data_name').value=document.filename;$('#brain-event-form').scrollIntoView({block:'start',behavior:'smooth'});}},'Link milestone →')),advanced('Recorded document links',document.links||[])));
  fill('#brain-view-documents',node('div',{class:'brain-action-heading'},node('h2',{text:'Original transaction evidence'}),badge('CONTENT-ADDRESSED LOCAL STORAGE','muted')),node('article',{class:'panel document-upload-panel'},node('div',{class:'panel-heading'},node('div',{},node('p',{class:'eyebrow',text:'EVIDENCE INTAKE'}),node('h2',{text:'Upload a document'}))),upload),node('div',{class:'document-grid',id:'brain-document-list'},cards.length?cards:blank('No documents linked to this property','Upload an original source document, then reference its ID in the relevant milestone or settlement note.')));
}
async function downloadDocument(identifier){const metadata=await request(`/api/documents/${encodeURIComponent(identifier)}`);const decoded=atob(metadata.content_base64||'');const bytes=new Uint8Array(decoded.length);for(let index=0;index<decoded.length;index++)bytes[index]=decoded.charCodeAt(index);const blob=new Blob([bytes],{type:metadata.media_type||'application/octet-stream'}),url=URL.createObjectURL(blob),anchor=node('a',{href:url,download:metadata.filename||`101XVC-evidence-${identifier}`});document.body.append(anchor);anchor.click();anchor.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}

async function loadQueue(){loading('#brain-view-queue');const response=await request('/api/brain/queue');const entries=rows(response);fill('#brain-view-queue',node('div',{class:'brain-action-heading'},node('h2',{text:'The next useful action'}),node('button',{class:'button small',onclick:event=>busy(event.currentTarget,loadQueue,'Refreshing…')},'↻ Refresh queue')),response.limitations?node('div',{class:'brain-banner',text:Array.isArray(response.limitations)?response.limitations.join(' '):written(response.limitations)}):null,node('div',{class:'brain-queue'},entries.length?entries.map((item,index)=>node('article',{class:'queue-card'},node('div',{class:'queue-index',text:String(index+1).padStart(2,'0')}),node('div',{class:'queue-main'},node('h3',{text:item.action||'Review transaction'}),node('p',{text:item.reason||'Review current transaction evidence.'}),node('small',{text:`${propertyName(item.property_id)} · ${item.calculation_label||'Evidence-based prioritization'}${item.score!=null?` · score ${item.score}`:''}`})),node('div',{class:'queue-actions'},badge(label(item.priority||'review'),item.priority==='urgent'?'red':'muted'),node('button',{class:'button small',onclick:async()=>{workspace.propertyId=item.property_id;workspace.episodeId=item.episode_id||'';await refreshContext();await switchTab('report');}},'Review report ↗')))):blank('No queued interventions','Create transaction episodes and record execution evidence to generate a daily review queue.')));}
async function loadPortfolio(){
  loading('#brain-view-portfolio');const response=await request('/api/brain/portfolio');const totals=response.totals||{};
  const highlights=[['TRANSACTION EPISODES',totals.episodes,written],['ACTIVE CONTRACTS',totals.active_contracts,written],['RECORDED COLLECTED CASH',totals.actual_collected_cash,cash],['SUPPORTED EXPECTED CONTRIBUTION',totals.supported_expected_contribution,cash]];
  const forecast=node('article',{class:'panel'},node('div',{class:'panel-heading'},node('div',{},node('p',{class:'eyebrow',text:'CASH TIMING'}),node('h2',{text:'Receipt forecast'}))),renderForecast(response.forecast),node('div',{class:'portfolio-concentration'},note(response.limitations)));
  const concentration=node('article',{class:'panel'},node('div',{class:'panel-heading'},node('div',{},node('p',{class:'eyebrow',text:'EXPOSURE + CAPACITY'}),node('h2',{text:'Concentration view'}))),renderConcentration(response.concentration),response.capacity?node('div',{class:'portfolio-concentration'},advanced('Review capacity constraints',response.capacity)):null);
  fill('#brain-view-portfolio',node('div',{class:'portfolio-totals'},highlights.map(([title,value,format])=>node('article',{class:'portfolio-total'},node('span',{text:title}),node('b',{text:format(value)})))),node('div',{class:'brain-banner',text:`${numeric(totals.episodes_with_unrecorded_cash)} episodes have unrecorded cash receipts. ${numeric(totals.episodes_pending_contribution_forecast)} episodes await sufficient contribution forecast evidence. Supported totals include only supported observations.`}),node('div',{class:'portfolio-grid'},forecast,concentration),node('article',{class:'panel',style:'margin-top:20px'},node('div',{class:'panel-heading'},node('div',{},node('p',{class:'eyebrow',text:'TRANSACTION ECONOMICS'}),node('h2',{text:'Episode-level economics'}))),renderPortfolioItems(rows(response))));
}
function renderForecast(forecast){if(!forecast||!Object.keys(forecast).length)return blank('Cash timing not established','Record funded settlements, actual receipt dates, and open transaction milestones.');const entries=Array.isArray(forecast)?forecast:Object.entries(forecast).map(([period,value])=>({period,...(typeof value==='object'?value:{expected_cash:value})}));return node('div',{class:'table-wrap'},node('table',{},node('thead',{},node('tr',{},...['WINDOW','SUPPORTED RECEIPTS','SUPPORTED / PENDING','STATUS'].map(title=>node('th',{text:title})))),node('tbody',{},entries.map(row=>node('tr',{},node('td',{text:row.period?`${row.period} days`:row.scenario||row.days||row.name||'Forecast'}),node('td',{text:cash(row.expected_cash??row.cash??row.expected_receipts)}),node('td',{text:`${numeric(row.supported_episodes)} / ${numeric(row.pending_episodes)}`}),node('td',{text:label(row.status||row.method||'Estimated')}))))));}
function renderConcentration(concentration){if(!concentration)return blank('No concentration evidence','Record market, partner, buyer, and settlement details.');const groups=Object.entries(concentration);return node('div',{class:'portfolio-concentration'},groups.map(([kind,value])=>node('section',{class:'concentration-group'},node('h3',{text:label(kind)}),Array.isArray(value)?value.map(item=>node('div',{class:'concentration-row'},node('span',{text:item.name||item.state||item.partner_id||item.buyer_id||item.key||'Unspecified'}),node('span',{text:item.count!=null?`${item.count} episodes`:cash(item.contribution??item.value)}))):typeof value==='object'?Object.entries(value).map(([name,total])=>node('div',{class:'concentration-row'},node('span',{text:name}),node('span',{text:typeof total==='object'?written(total.count??total.episodes??total.value):written(total)}))):note(value))));}
function renderPortfolioItems(entries){if(!entries.length)return blank('No episode economics yet','Transaction episodes with observed costs and settlements populate this view.');return node('div',{class:'table-wrap'},node('table',{},node('thead',{},node('tr',{},...['EPISODE','STAGE','RETAINED FEE','CONTRIBUTION','COLLECTED CASH'].map(title=>node('th',{text:title})))),node('tbody',{},entries.map(item=>node('tr',{},node('td',{text:item.episode_id||item.id||item.property_id}),node('td',{text:label(item.stage||'open')}),node('td',{text:cash(item.retained_fee??item.company_economics?.retained_fee)}),node('td',{text:cash(item.contribution??item.company_economics?.contribution)}),node('td',{text:cash(item.collected_cash??item.company_economics?.collected_cash)}))))));}

const modelKinds=['valuation','repairs','acceptance','closing','cash'];
async function loadModels(){loading('#brain-view-models');const response=await request('/api/brain/models');workspace.models=response.models||rows(response);workspace.activeModels=response.active||{};renderModelRegistry(response);}
function modelActive(model){if(model.active===true||model.status==='active'||model.stage==='production')return true;const active=workspace.activeModels;return Array.isArray(active)?active.some(item=>(typeof item==='string'?item:item.model_id)===model.model_id):Object.values(active).some(value=>(typeof value==='string'?value:value?.model_id)===model.model_id);}
function renderModelRegistry(response){
  const cards=workspace.models.map(model=>{
    const active=modelActive(model),metrics=model.validation?.metrics||model.metrics||{},gate=model.gate||{};
    return node('article',{class:`registry-model${active?' active':''}`},node('div',{class:'source-card-top'},badge(label(model.kind||'model'),'muted'),badge(active?'ACTIVE':label(model.status||'candidate'),active?'green':'muted')),node('h3',{text:label(model.algorithm||model.kind||'Independent statistical model')}),node('small',{text:model.model_id||model.id}),node('p',{text:`${model.synthetic?'Contains synthetic training evidence':'Observed training evidence'} · ${written(model.support?.train,'Unknown')} training rows · ${written(model.support?.validation,'Unknown')} later validation rows · ${written(model.support?.excluded,0)} excluded rows`}),Object.keys(metrics).length?advanced('Inspect chronological validation metrics',metrics):note('Evaluation metrics are not yet available.'),node('div',{class:'model-gates'},node('div',{class:'model-gate'},node('span',{class:gate.eligible?'pass':'fail',text:gate.eligible?'✓':'○'}),node('span',{text:gate.reason||'Promotion eligibility not established.'}))),note(model.limitations),node('div',{class:'model-actions'},node('button',{class:'button small primary',disabled:active||model.synthetic||gate.eligible!==true,id:`brain-promote-${model.model_id||model.id}`,onclick:event=>busy(event.currentTarget,async()=>{await request('/api/brain/models/promote',{method:'POST',body:JSON.stringify({model_id:model.model_id||model.id})});await loadModels();toast('Validated candidate promoted to the active registry.');},'Promoting…')},active?'Active model':'Promote candidate'),node('button',{class:'button small',disabled:active||model.status==='candidate'||model.synthetic,onclick:event=>busy(event.currentTarget,async()=>{await request('/api/brain/models/rollback',{method:'POST',body:JSON.stringify({kind:model.kind,model_id:model.model_id||model.id})});await loadModels();toast('Model rollback recorded.');},'Restoring…')},'Restore version')),advanced('Training provenance + registry metadata',model));
  });
  const trainForm=node('form',{id:'brain-model-train-form',class:'model-train-form'},inputField('kind','Candidate model family',{choices:modelKinds}),inputField('training_file','Optional labeled JSON dataset',{type:'file',accept:'.json,application/json'}),node('label',{class:'checkbox-label'},node('input',{type:'checkbox',name:'synthetic',id:'brain-model-synthetic'}),'Training dataset includes simulated outcomes'),node('p',{class:'form-note',text:'Leave the dataset empty to learn from the permanent ledger. Uploaded rows require property_id, decision_at, features, label, outcome_at, and label_available_at. Training uses later, separate properties for validation. Synthetic candidates cannot be promoted.'}),node('button',{type:'submit',class:'button primary',id:'brain-model-train'},'Build and evaluate candidate →'));
  trainForm.addEventListener('submit',event=>{event.preventDefault();busy($('button[type=submit]',trainForm),async()=>{const data={kind:trainForm.elements.namedItem('kind').value,synthetic:trainForm.elements.namedItem('synthetic').checked};const file=trainForm.elements.namedItem('training_file').files[0];if(file){if(file.size>10*1024*1024)throw new Error('Training JSON must be under 10 MB.');const parsed=JSON.parse(await file.text());data.rows=Array.isArray(parsed)?parsed:parsed.rows;if(!Array.isArray(data.rows))throw new Error('Dataset must contain a rows array or be an array of labeled examples.');data.synthetic=data.synthetic||parsed.synthetic===true;if(data.synthetic)data.rows=data.rows.map(row=>({...row,synthetic:true}));}const result=await request('/api/brain/models/train',{method:'POST',body:JSON.stringify(data)});await loadModels();toast(result.status==='insufficient_data'?result.reason||'More observed outcomes are needed before training.':`Candidate ${result.model_id||result.model?.model_id||''} evaluated. Review its metrics and promotion gates.`);},'Training…');});
  fill('#brain-view-models',node('div',{class:'brain-banner',text:'The registry separates estimates from learned predictions. Candidate models retain training provenance and evaluation gates. Promotion records a version change, and prior versions remain available for rollback.'}),node('div',{class:'brain-models-grid',id:'brain-registry-models'},cards.length?cards:blank('No candidate models yet','Record observed transaction outcomes, then train a candidate from the ledger.')),node('div',{class:'model-controls'},node('article',{class:'panel'},node('div',{class:'panel-heading'},node('div',{},node('p',{class:'eyebrow',text:'CONTROLLED LEARNING'}),node('h2',{text:'Train a candidate'}))),trainForm),node('article',{class:'panel'},node('div',{class:'panel-heading'},node('div',{},node('p',{class:'eyebrow',text:'ACTIVE MODEL LINEAGE'}),node('h2',{text:'Production versions'}))),node('div',{class:'portfolio-concentration'},advanced('Inspect active versions',response.active||{}),advanced('Registry evaluation policy',response.policy||response.gates||{})))));
}
async function loadRules(){loading('#brain-view-rules');const response=await request('/api/brain/rules');const entries=rows(response);const form=node('form',{class:'stack-form',id:'brain-rule-form'},node('div',{class:'form-pair'},inputField('jurisdiction','Jurisdiction',{required:true,placeholder:'US, CO, or five-digit county FIPS'}),inputField('state','State (optional)',{maxlength:2,pattern:'[A-Za-z]{2}',placeholder:'CO'})),node('div',{class:'form-pair'},inputField('effective_from','Effective from',{type:'date',required:true,value:new Date().toISOString().slice(0,10)}),inputField('effective_to','Effective through (optional)',{type:'date'})),node('div',{class:'form-pair'},inputField('status','Review status',{choices:['draft','reviewed']}),inputField('approved_by','Reviewed / approved by',{placeholder:'Required for reviewed rules'})),inputField('partner_id','Partner scope (optional)'),node('div',{class:'form-pair'},inputField('min_profit','Minimum gross spread ($)',{type:'number',min:0,value:'20000',required:true}),inputField('partner_split_pct','Partner share (%)',{type:'number',min:0,max:100,value:'50',required:true})),node('div',{class:'form-pair'},inputField('capacity','Maximum active contract units',{type:'number',min:0,placeholder:'No limit configured'}),inputField('max_cash_required','Cash required ceiling per transaction ($)',{type:'number',min:0,placeholder:'No limit configured'})),inputField('required_documents','Required documents',{type:'textarea',placeholder:'One document or approval per line'}),inputField('allowed_structures','Permitted transaction structures',{type:'textarea',placeholder:'One structure per line, such as assignment or novation'}),inputField('reason','Version / review reason',{type:'textarea',required:true}),node('details',{},node('summary',{class:'form-note',text:'Additional versioned rule fields'}),inputField('extra_rules','Additional rules (JSON object)',{type:'textarea'})),node('button',{type:'submit',class:'button primary',id:'brain-save-rule'},'Save rule version →'));
  form.addEventListener('submit',event=>{event.preventDefault();busy($('button[type=submit]',form),async()=>{const values=Object.fromEntries(new FormData(form));if(values.status==='reviewed'&&!values.approved_by.trim())throw new Error('Reviewed rules require the reviewer or approver identity.');const jurisdiction=values.jurisdiction.trim().toUpperCase();if(!/^(US|USA|ALL|FEDERAL|[A-Z]{2}|[0-9]{5})$/.test(jurisdiction))throw new Error('Use US, a two-letter state, or a five-digit county FIPS as the jurisdiction.');const rules={min_profit:numeric(values.min_profit),partner_split_pct:numeric(values.partner_split_pct),required_documents:values.required_documents.split('\n').map(value=>value.trim()).filter(Boolean)};if(values.allowed_structures.trim())rules.allowed_structures=values.allowed_structures.split('\n').map(value=>value.trim()).filter(Boolean);for(const key of ['capacity','max_cash_required'])if(values[key]!=='')rules[key]=numeric(values[key]);if(values.extra_rules.trim()){const extra=JSON.parse(values.extra_rules);if(!extra||typeof extra!=='object'||Array.isArray(extra))throw new Error('Additional rules must be a JSON object.');Object.assign(rules,extra);}const data={jurisdiction,state:values.state.toUpperCase(),effective_from:values.effective_from,status:values.status,approved_by:values.approved_by,partner_id:values.partner_id,reason:values.reason,rules,...(values.effective_to?{effective_to:values.effective_to}:{})};await request('/api/brain/rules',{method:'POST',body:JSON.stringify(data)});await loadRules();toast('Versioned contract rule saved.');},'Saving…');});
  fill('#brain-view-rules',node('div',{class:'brain-banner',text:'Contract rules are separate from statistical models. Apply reviewed, effective rules to the correct jurisdiction and partner. Record exceptions and reviewer identity.'}),node('div',{class:'brain-rules',id:'brain-rule-versions'},entries.length?entries.map(rule=>node('article',{class:'rule-card'},node('div',{class:'source-card-top'},badge(label(rule.status||'draft'),rule.status==='reviewed'?'green':'muted'),badge(`VERSION ${String(rule.version||rule.id||'').slice(0,16)}`,'muted')),node('h3',{text:rule.jurisdiction||rule.name||'Contract rule'}),node('p',{text:`Effective ${written(rule.effective_from)}${rule.effective_to?` through ${rule.effective_to}`:''} · ${rule.state||'All matching states'}${rule.partner_id?` · partner ${rule.partner_id}`:''}`}),node('small',{text:`Reviewer ${rule.approved_by||'Not recorded'} · ${rule.reason||'No review reason recorded'}`}),advanced('Inspect reviewed requirements',rule.rules||rule))):blank('No rule versions configured','Create a reviewed rule version before relying on jurisdiction or partner approval constraints.')),node('article',{class:'panel brain-rule-form'},node('div',{class:'panel-heading'},node('div',{},node('p',{class:'eyebrow',text:'RULE GOVERNANCE'}),node('h2',{text:'Create a rule version'}))),form));}
